"""empty message

Revision ID: 1778dbaaefca
Revises: 
Create Date: 2026-02-02 22:00:25.924632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1778dbaaefca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FirstName', sa.String(length=150), nullable=True))
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('FirstName')

    # ### end Alembic commands ###
